// Locates agent-note quotes inside the rendered investigation result. The
// result HTML is regenerated by the agent, so notes are anchored by their
// quoted text (plus a little surrounding context) rather than DOM positions.
// Matching ignores whitespace entirely so reflowed or re-indented HTML, and
// selections that span block boundaries, still resolve.

export const BLOCK_SELECTOR = "h1,h2,h3,h4,h5,h6,p,li,tr,pre,blockquote,dt,dd,figcaption";
const CONTEXT_CHARS = 24;

export type TextIndex = {
  /** Document text with all whitespace removed. */
  text: string;
  /** For each character of `text`, the text node and offset it came from. */
  map: Array<[Text, number]>;
};

export type QuoteAnchor = {
  quote: string;
  prefix: string;
  suffix: string;
  /** Start of the quote in `TextIndex.text`; tells repeated text apart. */
  offset: number;
};

const WHITESPACE = /\s/;
export const stripWhitespace = (value: string) => value.replace(/\s+/g, "");
export const collapseWhitespace = (value: string) => value.replace(/\s+/g, " ").trim();

export function buildTextIndex(doc: Document): TextIndex {
  const walker = doc.createTreeWalker(doc.body, NodeFilter.SHOW_TEXT, {
    acceptNode: (node) =>
      node.parentElement?.closest("script,style,noscript")
        ? NodeFilter.FILTER_REJECT
        : NodeFilter.FILTER_ACCEPT,
  });
  let text = "";
  const map: Array<[Text, number]> = [];
  for (let node = walker.nextNode(); node; node = walker.nextNode()) {
    const value = node.nodeValue ?? "";
    for (let offset = 0; offset < value.length; offset++) {
      if (!WHITESPACE.test(value[offset])) {
        text += value[offset];
        map.push([node as Text, offset]);
      }
    }
  }
  return { text, map };
}

/** Leaf block elements used for keyboard block navigation. */
export function listBlocks(doc: Document): HTMLElement[] {
  return [...doc.body.querySelectorAll<HTMLElement>(BLOCK_SELECTOR)].filter(
    (el) => el.textContent?.trim() && !el.querySelector(BLOCK_SELECTOR),
  );
}

/** Index in `index.text` of the first non-whitespace character at or after the range start. */
function rangeStartIndex(index: TextIndex, range: Range): number {
  const found = index.map.findIndex(([node, offset]) => {
    const position = range.comparePoint(node, offset);
    return position >= 0;
  });
  return found < 0 ? index.text.length : found;
}

export function anchorFromRange(index: TextIndex, range: Range): QuoteAnchor | null {
  const quote = collapseWhitespace(range.toString());
  const length = stripWhitespace(quote).length;
  if (!length) return null;
  const start = rangeStartIndex(index, range);
  return {
    quote,
    prefix: index.text.slice(Math.max(0, start - CONTEXT_CHARS), start),
    suffix: index.text.slice(start + length, start + length + CONTEXT_CHARS),
    offset: start,
  };
}

/**
 * Finds the quote in the current document. With several occurrences, the one
 * whose surrounding context matches wins, then the one nearest the recorded
 * offset (the result may have shifted a little since the note was written).
 */
export function locateQuote(
  doc: Document,
  index: TextIndex,
  anchor: {
    quote: string | null;
    prefix?: string | null;
    suffix?: string | null;
    offset?: number | null;
  },
): Range | null {
  if (!anchor.quote) return null;
  const needle = stripWhitespace(anchor.quote);
  if (!needle) return null;
  const prefix = stripWhitespace(anchor.prefix ?? "");
  const suffix = stripWhitespace(anchor.suffix ?? "");
  let start = -1;
  let best = -Infinity;
  for (let at = index.text.indexOf(needle); at >= 0; at = index.text.indexOf(needle, at + 1)) {
    const context =
      (prefix && index.text.slice(Math.max(0, at - prefix.length), at) === prefix ? 2 : 0) +
      (suffix && index.text.startsWith(suffix, at + needle.length) ? 2 : 0);
    const distance = anchor.offset == null ? 0 : Math.abs(at - anchor.offset) / (index.text.length + 1);
    const score = context - distance;
    if (score > best) {
      best = score;
      start = at;
    }
  }
  if (start < 0) return null;
  const [startNode, startOffset] = index.map[start];
  const [endNode, endOffset] = index.map[start + needle.length - 1];
  const range = doc.createRange();
  range.setStart(startNode, startOffset);
  range.setEnd(endNode, endOffset + 1);
  return range;
}

/** Short fingerprint of the result HTML, to tell whether it changed since a note. */
export function hashResult(html: string): string {
  let hash = 0x811c9dc5;
  for (let i = 0; i < html.length; i++) {
    hash ^= html.charCodeAt(i);
    hash = Math.imul(hash, 0x01000193);
  }
  return (hash >>> 0).toString(16).padStart(8, "0");
}

export function blockSpanRange(doc: Document, blocks: HTMLElement[], a: number, b: number): Range {
  const range = doc.createRange();
  range.setStartBefore(blocks[Math.min(a, b)]);
  range.setEndAfter(blocks[Math.max(a, b)]);
  return range;
}
