// Locates agent-note quotes inside the rendered investigation result. The
// result HTML is regenerated by the agent, so notes are anchored by their
// quoted text (plus a little surrounding context) rather than DOM positions.
// Matching ignores whitespace entirely so reflowed or re-indented HTML, and
// selections that span block boundaries, still resolve.

export const BLOCK_SELECTOR = "h1,h2,h3,h4,h5,h6,p,li,tr,pre,blockquote,dt,dd,figcaption";
const CONTEXT_CHARS = 24;

export type TextIndex = {
  /** Document text with all whitespace removed. */
  text: string;
  /** For each character of `text`, the text node and offset it came from. */
  map: Array<[Text, number]>;
};

export type QuoteAnchor = {
  quote: string;
  prefix: string;
  suffix: string;
};

const WHITESPACE = /\s/;
export const stripWhitespace = (value: string) => value.replace(/\s+/g, "");
export const collapseWhitespace = (value: string) => value.replace(/\s+/g, " ").trim();

export function buildTextIndex(doc: Document): TextIndex {
  const walker = doc.createTreeWalker(doc.body, NodeFilter.SHOW_TEXT, {
    acceptNode: (node) =>
      node.parentElement?.closest("script,style,noscript")
        ? NodeFilter.FILTER_REJECT
        : NodeFilter.FILTER_ACCEPT,
  });
  let text = "";
  const map: Array<[Text, number]> = [];
  for (let node = walker.nextNode(); node; node = walker.nextNode()) {
    const value = node.nodeValue ?? "";
    for (let offset = 0; offset < value.length; offset++) {
      if (!WHITESPACE.test(value[offset])) {
        text += value[offset];
        map.push([node as Text, offset]);
      }
    }
  }
  return { text, map };
}

/** Leaf block elements used for keyboard block navigation. */
export function listBlocks(doc: Document): HTMLElement[] {
  return [...doc.body.querySelectorAll<HTMLElement>(BLOCK_SELECTOR)].filter(
    (el) => el.textContent?.trim() && !el.querySelector(BLOCK_SELECTOR),
  );
}

/** Index in `index.text` of the first non-whitespace character at or after the range start. */
function rangeStartIndex(index: TextIndex, range: Range): number {
  const found = index.map.findIndex(([node, offset]) => {
    const position = range.comparePoint(node, offset);
    return position >= 0;
  });
  return found < 0 ? index.text.length : found;
}

export function anchorFromRange(index: TextIndex, range: Range): QuoteAnchor | null {
  const quote = collapseWhitespace(range.toString());
  const length = stripWhitespace(quote).length;
  if (!length) return null;
  const start = rangeStartIndex(index, range);
  return {
    quote,
    prefix: index.text.slice(Math.max(0, start - CONTEXT_CHARS), start),
    suffix: index.text.slice(start + length, start + length + CONTEXT_CHARS),
  };
}

/** Finds the quote in the current document, preferring the occurrence whose context matches. */
export function locateQuote(
  doc: Document,
  index: TextIndex,
  anchor: { quote: string | null; prefix?: string | null; suffix?: string | null },
): Range | null {
  if (!anchor.quote) return null;
  const needle = stripWhitespace(anchor.quote);
  if (!needle) return null;
  const prefix = stripWhitespace(anchor.prefix ?? "");
  const suffix = stripWhitespace(anchor.suffix ?? "");
  let start = -1;
  if (prefix) {
    const at = index.text.indexOf(prefix + needle);
    if (at >= 0) start = at + prefix.length;
  }
  if (start < 0 && suffix) start = index.text.indexOf(needle + suffix);
  if (start < 0) start = index.text.indexOf(needle);
  if (start < 0) return null;
  const [startNode, startOffset] = index.map[start];
  const [endNode, endOffset] = index.map[start + needle.length - 1];
  const range = doc.createRange();
  range.setStart(startNode, startOffset);
  range.setEnd(endNode, endOffset + 1);
  return range;
}

export function blockSpanRange(doc: Document, blocks: HTMLElement[], a: number, b: number): Range {
  const range = doc.createRange();
  range.setStartBefore(blocks[Math.min(a, b)]);
  range.setEndAfter(blocks[Math.max(a, b)]);
  return range;
}
